// frontend-angular/src/app/pages/admin-table-toolbar.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

export type AdminFilterOption = { value: string; label: string };
export type AdminFilterDef = {
  key: string;
  label: string;
  value: string;
  options: AdminFilterOption[];
};

@Component({
  selector: 'app-admin-table-toolbar',
  standalone: true,
  template: `
    <div class="admin-toolbar" [class.is-loading]="loading">
      <div class="admin-toolbar-row">
        <label class="admin-search">
          <span class="sr-only">Search</span>
          <input
            type="search"
            [value]="search"
            [placeholder]="searchPlaceholder"
            (input)="searchChange.emit(($any($event.target)).value)"
          />
        </label>
        @for (f of filters; track f.key) {
          <label class="admin-filter">
            <span>{{ f.label }}</span>
            <select
              [value]="f.value"
              (change)="filterChange.emit({ key: f.key, value: ($any($event.target)).value })"
            >
              @for (o of f.options; track o.value || 'all') {
                <option [value]="o.value">{{ o.label }}</option>
              }
            </select>
          </label>
        }
      </div>
      @if (!filtersOnly) {
        <div class="admin-pager">
          <button
            type="button"
            class="btn"
            [disabled]="page <= 1 || loading"
            (click)="pageChange.emit(page - 1)"
          >
            Prev
          </button>
          <span class="meta">
            Page {{ page }} of {{ totalPages < 1 ? 1 : totalPages }} · {{ total }} total
            @if (loading) {
              <span> · Updating…</span>
            }
          </span>
          <button
            type="button"
            class="btn"
            [disabled]="page >= totalPages || loading || total === 0"
            (click)="pageChange.emit(page + 1)"
          >
            Next
          </button>
          <label class="admin-filter admin-filter-inline">
            <span>Rows</span>
            <select
              [value]="pageSize"
              [disabled]="loading"
              (change)="pageSizeChange.emit(+$any($event.target).value)"
            >
              @for (n of pageSizes; track n) {
                <option [value]="n">{{ n }}</option>
              }
            </select>
          </label>
        </div>
      }
    </div>
  `,
})
export class AdminTableToolbarComponent {
  @Input() search = '';
  @Input() searchPlaceholder = 'Search…';
  @Input() filters: AdminFilterDef[] = [];
  @Input() page = 1;
  @Input() pageSize = 20;
  @Input() total = 0;
  @Input() totalPages = 1;
  @Input() loading = false;
  @Input() filtersOnly = false;

  @Output() searchChange = new EventEmitter<string>();
  @Output() filterChange = new EventEmitter<{ key: string; value: string }>();
  @Output() pageChange = new EventEmitter<number>();
  @Output() pageSizeChange = new EventEmitter<number>();

  readonly pageSizes = [10, 20, 50, 100];
}

@Component({
  selector: 'app-admin-pager',
  standalone: true,
  template: `
    <div class="admin-pager">
      <button
        type="button"
        class="btn"
        [disabled]="page <= 1 || loading"
        (click)="pageChange.emit(page - 1)"
      >
        Prev
      </button>
      <span class="meta">
        Page {{ page }} of {{ totalPages < 1 ? 1 : totalPages }} · {{ total }} total
        @if (loading) {
          <span> · Updating…</span>
        }
      </span>
      <button
        type="button"
        class="btn"
        [disabled]="page >= totalPages || loading || total === 0"
        (click)="pageChange.emit(page + 1)"
      >
        Next
      </button>
      <label class="admin-filter admin-filter-inline">
        <span>Rows</span>
        <select
          [value]="pageSize"
          [disabled]="loading"
          (change)="pageSizeChange.emit(+$any($event.target).value)"
        >
          @for (n of pageSizes; track n) {
            <option [value]="n">{{ n }}</option>
          }
        </select>
      </label>
    </div>
  `,
})
export class AdminPagerComponent {
  @Input() page = 1;
  @Input() pageSize = 20;
  @Input() total = 0;
  @Input() totalPages = 1;
  @Input() loading = false;

  @Output() pageChange = new EventEmitter<number>();
  @Output() pageSizeChange = new EventEmitter<number>();

  readonly pageSizes = [10, 20, 50, 100];
}

@Component({
  selector: 'th[appAdminSort]',
  standalone: true,
  template: `
    <button type="button" class="admin-sort" [class.on]="active" (click)="sort.emit(column)">
      {{ label }}{{ active ? (sortDir === 'asc' ? ' ↑' : ' ↓') : '' }}
    </button>
  `,
  host: { style: 'padding: 0' },
})
export class AdminSortThComponent {
  @Input({ required: true }) label!: string;
  @Input({ required: true }) column!: string;
  @Input() sortBy = '';
  @Input() sortDir = 'desc';
  @Output() sort = new EventEmitter<string>();

  get active() {
    return this.sortBy === this.column;
  }
}

// frontend/components/admin/AdminTableToolbar.tsx
'use client';

type FilterOption = { value: string; label: string };

type PagerProps = {
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
  onPageChange: (page: number) => void;
  onPageSizeChange: (size: number) => void;
  loading?: boolean;
};

export function AdminPager({
  page,
  pageSize,
  total,
  totalPages,
  onPageChange,
  onPageSizeChange,
  loading,
}: PagerProps) {
  return (
    <div className="admin-pager">
      <button type="button" className="btn" disabled={page <= 1 || loading} onClick={() => onPageChange(page - 1)}>
        Prev
      </button>
      <span className="meta">
        Page {page} of {Math.max(1, totalPages)} · {total} total
        {loading ? ' · Updating…' : ''}
      </span>
      <button
        type="button"
        className="btn"
        disabled={page >= totalPages || loading || total === 0}
        onClick={() => onPageChange(page + 1)}
      >
        Next
      </button>
      <label className="admin-filter admin-filter-inline">
        <span>Rows</span>
        <select
          value={pageSize}
          disabled={loading}
          onChange={(e) => onPageSizeChange(Number(e.target.value))}
        >
          {[10, 20, 50, 100].map((n) => (
            <option key={n} value={n}>
              {n}
            </option>
          ))}
        </select>
      </label>
    </div>
  );
}

type Props = {
  search: string;
  onSearchChange: (v: string) => void;
  searchPlaceholder?: string;
  filters?: { key: string; label: string; value: string; options: FilterOption[] }[];
  onFilterChange?: (key: string, value: string) => void;
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
  onPageChange: (page: number) => void;
  onPageSizeChange: (size: number) => void;
  loading?: boolean;
  /** When true, only render search/filters (pager rendered separately). */
  filtersOnly?: boolean;
};

export function AdminTableToolbar({
  search,
  onSearchChange,
  searchPlaceholder = 'Search…',
  filters = [],
  onFilterChange,
  page,
  pageSize,
  total,
  totalPages,
  onPageChange,
  onPageSizeChange,
  loading,
  filtersOnly,
}: Props) {
  return (
    <div className={`admin-toolbar${loading ? ' is-loading' : ''}`}>
      <div className="admin-toolbar-row">
        <label className="admin-search">
          <span className="sr-only">Search</span>
          <input
            type="search"
            value={search}
            placeholder={searchPlaceholder}
            onChange={(e) => onSearchChange(e.target.value)}
          />
        </label>
        {filters.map((f) => (
          <label key={f.key} className="admin-filter">
            <span>{f.label}</span>
            <select
              value={f.value}
              onChange={(e) => onFilterChange?.(f.key, e.target.value)}
            >
              {f.options.map((o) => (
                <option key={o.value || 'all'} value={o.value}>
                  {o.label}
                </option>
              ))}
            </select>
          </label>
        ))}
      </div>
      {!filtersOnly && (
        <AdminPager
          page={page}
          pageSize={pageSize}
          total={total}
          totalPages={totalPages}
          onPageChange={onPageChange}
          onPageSizeChange={onPageSizeChange}
          loading={loading}
        />
      )}
    </div>
  );
}

export function SortTh({
  label,
  column,
  sortBy,
  sortDir,
  onSort,
}: {
  label: string;
  column: string;
  sortBy: string;
  sortDir: string;
  onSort: (column: string) => void;
}) {
  const active = sortBy === column;
  return (
    <th>
      <button type="button" className={`admin-sort${active ? ' on' : ''}`} onClick={() => onSort(column)}>
        {label}
        {active ? (sortDir === 'asc' ? ' ↑' : ' ↓') : ''}
      </button>
    </th>
  );
}
